In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
! find ../../  | grep Churn

../../datasets/machine_learning_a-z/P14-Artificial-Neural-Networks/Artificial_Neural_Networks/Churn_Modelling.csv
../../datasets/machine_learning_a-z/P14-Artificial-Neural-Networks/__MACOSX/Artificial_Neural_Networks/._Churn_Modelling.csv
../../datasets/machine_learning_a-z/P14-XGBoost/__MACOSX/XGBoost/._Churn_Modelling.csv
../../datasets/machine_learning_a-z/P14-XGBoost/XGBoost/Churn_Modelling.csv
../../datasets/deep_learning_a-z/P16-Artificial-Neural-Networks/Artificial_Neural_Networks/Churn_Modelling.csv
../../datasets/deep_learning_a-z/P16-Artificial-Neural-Networks/__MACOSX/Artificial_Neural_Networks/._Churn_Modelling.csv


In [30]:
dataset = pd.read_csv('../../datasets/machine_learning_a-z/P14-Artificial-Neural-Networks/Artificial_Neural_Networks/Churn_Modelling.csv')

In [31]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [32]:
X= dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

### Feature Engineer
Encode categorical data

In [33]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

Gender and Geography have to be encoded, two label encoder needed

In [34]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# For two
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_1.fit_transform(X[:,2])

In [35]:
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [36]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

/home/wajeeh-ros/.conda/envs/python3/lib/python2.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/wajeeh-ros/.conda/envs/python3/lib/python2.7/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


PRINT THE ARRAY AS DATAFRAME FOR EXPLORATION

In [43]:
pd.DataFrame(X).head()

0    1    2      3    4     5    6          7    8    9    10         11
0  1.0  0.0  0.0  619.0  0.0  42.0  2.0       0.00  1.0  1.0  1.0  101348.88
1  0.0  0.0  1.0  608.0  0.0  41.0  1.0   83807.86  1.0  0.0  1.0  112542.58
2  1.0  0.0  0.0  502.0  0.0  42.0  8.0  159660.80  3.0  1.0  0.0  113931.57
3  1.0  0.0  0.0  699.0  0.0  39.0  1.0       0.00  2.0  0.0  0.0   93826.63
4  0.0  0.0  1.0  850.0  0.0  43.0  2.0  125510.82  1.0  1.0  1.0   79084.10

In [44]:
X=X[:,1:]

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,
                                                    random_state=0)

### FEATURE SCALING
important for neural network<br>
fit method fits the data<br>
transofm then transforms it<br>
fit_transform fits and transofms it,<br>
if already fitted_transformed then we dont have to fit again


In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##### BUILD ANN 

In [49]:
import keras

Using TensorFlow backend.


In [50]:
from keras.models import Sequential
from keras.layers import Dense

In [51]:
classifier = Sequential()

Dense(self, units, activation=None, use_bias=True, kernel_initializer='glorot_uniform', bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, bias_constraint=None, **kwargs)

##### optimal number of nodes is  PARAMETER TUNING
k-fold is useful (arts)

In [53]:
#input dim have to be specified for the first layer
classifier.add(Dense(input_dim=11,
                     output_dim=6, init = 'uniform'
                     , activation='relu'))

/home/wajeeh-ros/.conda/envs/python3/lib/python2.7/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", input_dim=11, units=6)`
  after removing the cwd from sys.path.


In [54]:
#input dim have to be specified for the first layer
classifier.add(Dense(output_dim=6, init = 'uniform'
                     , activation='relu'))

/home/wajeeh-ros/.conda/envs/python3/lib/python2.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [56]:
#input dim have to be specified for the first layer
classifier.add(Dense(output_dim=1, init = 'uniform'
                     , activation='sigmoid'))

/home/wajeeh-ros/.conda/envs/python3/lib/python2.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [57]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',
                  metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [59]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 10s 1ms/step - loss: 0.4847 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 2s 281us/step - loss: 0.4288 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 285us/step - loss: 0.4217 - acc: 0.8015
Epoch 4/100
8000/8000 [==============================] - 2s 279us/step - loss: 0.4179 - acc: 0.8209
Epoch 5/100
8000/8000 [==============================] - 2s 276us/step - loss: 0.4150 - acc: 0.8282
Epoch 6/100
8000/8000 [==============================] - 2s 283us/step - loss: 0.4140 - acc: 0.8306
Epoch 7/100
8000/8000 [==============================] - 2s 276us/step - loss: 0.4122 - acc: 0.8334
Epoch 8/100
8000/8000 [==============================] - 2s 287us/step - loss: 0.4107 - acc: 0.8346
Epoch 9/100
8000/8000 [==============================] - 2s 276us/step - loss: 0.4101 - acc: 0.8326
Epoch 10/100
8000/8000 [=============================

8000/8000 [==============================] - 2s 286us/step - loss: 0.4009 - acc: 0.8369
Epoch 80/100
8000/8000 [==============================] - 2s 274us/step - loss: 0.4006 - acc: 0.8339
Epoch 81/100
8000/8000 [==============================] - 2s 277us/step - loss: 0.4008 - acc: 0.8340
Epoch 82/100
8000/8000 [==============================] - 2s 276us/step - loss: 0.4007 - acc: 0.8354
Epoch 83/100
8000/8000 [==============================] - 2s 276us/step - loss: 0.4010 - acc: 0.8332
Epoch 84/100
8000/8000 [==============================] - 2s 272us/step - loss: 0.4007 - acc: 0.8340
Epoch 85/100
8000/8000 [==============================] - 2s 280us/step - loss: 0.4004 - acc: 0.8351
Epoch 86/100
8000/8000 [==============================] - 2s 272us/step - loss: 0.4008 - acc: 0.8341
Epoch 87/100
8000/8000 [==============================] - 2s 275us/step - loss: 0.4013 - acc: 0.8362
Epoch 88/100
8000/8000 [==============================] - 2s 277us/step - loss: 0.4010 - acc: 0.8347
Epo

In [60]:
y_pred = classifier.predict(X_test)

In [61]:
y_pred = (y_pred > 0.5)

In [62]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [63]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [64]:
cm

array([[1531,   64],
       [ 248,  157]])

In [69]:
(1531 + 157)

1688