In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
! find ../../  | grep Churn

../../deep learning/dlaz/.ipynb_checkpoints/Artificial Neural Network - Bank Churn Data-checkpoint.ipynb
../../deep learning/dlaz/Artificial Neural Network - Bank Churn Data.ipynb
../../datasets/machine_learning_a-z/P14-XGBoost/__MACOSX/XGBoost/._Churn_Modelling.csv
../../datasets/machine_learning_a-z/P14-XGBoost/XGBoost/Churn_Modelling.csv
../../datasets/machine_learning_a-z/P14-Artificial-Neural-Networks/Artificial_Neural_Networks/Churn_Modelling.csv
../../datasets/machine_learning_a-z/P14-Artificial-Neural-Networks/__MACOSX/Artificial_Neural_Networks/._Churn_Modelling.csv
../../datasets/deep_learning_a-z/P16-Artificial-Neural-Networks/Artificial_Neural_Networks/Churn_Modelling.csv
../../datasets/deep_learning_a-z/P16-Artificial-Neural-Networks/__MACOSX/Artificial_Neural_Networks/._Churn_Modelling.csv


In [3]:
dataset = pd.read_csv('../../datasets/machine_learning_a-z/P14-Artificial-Neural-Networks/Artificial_Neural_Networks/Churn_Modelling.csv')

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X= dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

### Feature Engineer
Encode categorical data

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

Gender and Geography have to be encoded, two label encoder needed

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# For two
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_1.fit_transform(X[:,2])

In [8]:
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [17]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

TypeError: __init__() got an unexpected keyword argument 'categorical_features'

PRINT THE ARRAY AS DATAFRAME FOR EXPLORATION

In [18]:
pd.DataFrame(X).head()

0  1  2   3  4        5  6  7  8        9
0  619  0  0  42  2        0  1  1  1   101349
1  608  2  0  41  1  83807.9  1  0  1   112543
2  502  0  0  42  8   159661  3  1  0   113932
3  699  0  0  39  1        0  2  0  0  93826.6
4  850  2  0  43  2   125511  1  1  1  79084.1

In [19]:
X=X[:,1:]

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,
                                                    random_state=0)

### FEATURE SCALING
important for neural network<br>
fit method fits the data<br>
transofm then transforms it<br>
fit_transform fits and transofms it,<br>
if already fitted_transformed then we dont have to fit again


In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##### BUILD ANN 

In [ ]:
import keras

In [10]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [11]:
classifier = Sequential()

Dense(self, units, activation=None, use_bias=True, kernel_initializer='glorot_uniform', bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, bias_constraint=None, **kwargs)

##### optimal number of nodes is  PARAMETER TUNING
k-fold is useful (arts)

In [12]:
#input dim have to be specified for the first layer
classifier.add(Dense(input_dim=11,
                     output_dim=6, init = 'uniform'
                     , activation='relu'))

/home/wajeeh-machine/anaconda3/envs/mypython3/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.


In [13]:
#input dim have to be specified for the first layer
classifier.add(Dense(output_dim=6, init = 'uniform'
                     , activation='relu'))

/home/wajeeh-machine/anaconda3/envs/mypython3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [14]:
#input dim have to be specified for the first layer
classifier.add(Dense(output_dim=1, init = 'uniform'
                     , activation='sigmoid'))

/home/wajeeh-machine/anaconda3/envs/mypython3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [15]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',
                  metrics = ['accuracy'])

In [16]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

NameError: name 'X_train' is not defined

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_pred = (y_pred > 0.5)

In [ ]:
y_pred

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
cm

In [ ]:
(1531 + 157)