# GTest numpy

### Create numpy arrays from Python arrays

In [5]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Get type of objects in array
x.dtype

dtype('int32')

In [4]:
# Get tuple of dimensions
x.shape

(5,)

In [6]:
# Multi-dimension
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
# Get tuple of dimensions
y.shape

(4, 3)

In [8]:
# Get number of elements
y.size

12

In [10]:
# Strings
x = np.array(['hello', 'world'])
print(x)

['hello' 'world']


In [11]:
print(x.shape)
print(type(x))
print(x.dtype)

(2,)
<class 'numpy.ndarray'>
<U5


In [13]:
# Combining types -> casts to a common type
x = np.array([1, 2, 'world'])
print(x)

['1' '2' 'world']


In [14]:
print(x.shape)
print(type(x))
print(x.dtype)

(3,)
<class 'numpy.ndarray'>
<U11


In [15]:
# Combine int and float
x = np.array([1, 2, 3.5])
print(x, x.dtype)

[ 1.   2.   3.5] float64


In [16]:
# Specify the dtype
x = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(x, x.dtype)

[1 2 3] int64


In [17]:
# Save and load array to/from file
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [18]:
np.save('my_array', x)

In [20]:
y = np.load('my_array.npy')
print(y)

[1 2 3]


### Create numpy arrays from numpy functions

In [21]:
# np.zeros -> create array with 0s
x = np.zeros((3, 4))
print(x)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [22]:
x = np.zeros((3, 4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [23]:
# np.ones -> create array with 1s
x = np.ones((3, 4), dtype=int)
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [27]:
# np.full -> create array with whatever value you want
x = np.full((4, 3), 5, dtype=float)
print(x)

[[ 5.  5.  5.]
 [ 5.  5.  5.]
 [ 5.  5.  5.]
 [ 5.  5.  5.]]


In [30]:
# Create identity matrix (1s at the diagonals)
x = np.eye(5, dtype=np.int64)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [31]:
# Create matrix using diag
x = np.diag([10, 20, 30, 40])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [32]:
# a-range; creates a one dimensional array of evenly spaced values within a given interval
x = np.arange(10) # start, stop, step (1 arg = stop)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
# a-range; creates a one dimensional array of evenly spaced values within a given interval
x = np.arange(4, 10) # start, stop, step (2 arg = start, stop)
print(x)

[4 5 6 7 8 9]


In [34]:
# a-range; creates a one dimensional array of evenly spaced values within a given interval
x = np.arange(0, 10, 2) # start, stop, step
print(x)

[0 2 4 6 8]


In [35]:
# linspace; start, stop, n; returns n evenly spaced numbers from start to stop, both being inclusive
x = np.linspace(0, 25, 10)
print(x)

[  0.           2.77777778   5.55555556   8.33333333  11.11111111
  13.88888889  16.66666667  19.44444444  22.22222222  25.        ]


In [36]:
# linspace; endpoint = false removes the stop point
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[  0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5]


In [37]:
# reshape to create new shapes from existing
x = np.arange(20)
print(x)
x = np.reshape(x, (4,5)) # must reshape to a size that matches the number of elements
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
x = np.arange(20).reshape((4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [39]:
# create array of given shape with random floats between 0 (inclusive) and 1 (exclusive)
x = np.random.random((3, 3))
print(x)

[[ 0.03890013  0.10075402  0.12967757]
 [ 0.36946049  0.49378172  0.31209167]
 [ 0.1438231   0.84885865  0.81037039]]


In [40]:
x = np.random.randint(4, 15, (3, 2))
print(x)

[[ 5 11]
 [ 8 10]
 [ 7 13]]


In [41]:
# create random arrays with numbers drawn from various probability distributions
# random floats drawn from a *normal* (method name) distribution
# mean = 0, standard deviation = 0.1
x = np.random.normal(0, 0.1, size=(1000,1000))
print(x)

[[-0.00971866  0.02328695  0.043031   ...,  0.0387662  -0.07398276
  -0.0699223 ]
 [ 0.19471698  0.1876743   0.02097931 ...,  0.02936617  0.00545575
  -0.03130145]
 [-0.12973655 -0.04333256 -0.06085671 ...,  0.13379239 -0.14498845
  -0.06693247]
 ..., 
 [ 0.0528511  -0.00928591  0.08531163 ...,  0.0526751   0.09882972
  -0.06035401]
 [ 0.02113408  0.10904542 -0.09766419 ...,  0.06205765 -0.03810671
   0.25739763]
 [-0.03230024 -0.2116374   0.04848389 ...,  0.07004614  0.05575754
  -0.15819217]]


In [44]:
print(x.mean())
print(x.std())
print(x.max())
print(x.min())
print((x > 0).sum())
print((x < 0).sum())

0.000103146512259
0.0998664769741
0.477216978982
-0.472506742047
500206
499794


### Accessing, Deleting and Inserting Elements into ndarrays

In [45]:
# access by index
x = np.array([1, 2, 3, 4, 5])
print(x[0])
print(x[-1])

1
5


In [46]:
x[-1] = 20
print(x)

[ 1  2  3  4 20]


In [48]:
# multi-dimensional
x = np.arange(1, 10).reshape((3, 3))
print(x)
print(x[0, 0])
print(x[1, 1])
print(x[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
5
9


In [49]:
x[0, 0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [50]:
# delete elements
x = np.array([1, 2, 3, 4, 5])
print(x)
x = np.delete(x, [0, 4]) # delete first and 5th elements
print(x)

[1 2 3 4 5]
[2 3 4]


In [52]:
# delete elements -> multi-dimensional
x = np.arange(1, 10).reshape((3, 3))
print(x)

y = np.delete(x, 0, axis=0) # delete the first row; axis=0 -> row
print('\n', y)

z = np.delete(y, [0, 2], axis=1) # delete the first and third columns; axis=1 -> column
print('\n', z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[5]
 [8]]


In [57]:
# add values using append (array, list of elements to append, axis to append it on)
x = np.arange(1, 6)
print(x)

x = np.append(x, 6)
print(x)

x = np.append(x, [7, 8])
print(x)


[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [68]:
# add values on rank 2 array
x = np.arange(1, 10).reshape((3, 3))
print(x)

# add a row
x = np.append(x, [[10, 11, 12]], axis=0)
print('\n', x)

# add a column
x = np.append(x, [[97], [98], [99], [100]], axis=1)
print('\n', x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[  1   2   3  97]
 [  4   5   6  98]
 [  7   8   9  99]
 [ 10  11  12 100]]


In [69]:
# insert into the middle of an array
# insert function ... args = array, index, elements, axis
x = np.array([1, 2, 5, 6, 7])
print(x)

x = np.insert(x, 2, [3, 4], axis=0)
print(x)

[1 2 5 6 7]
[1 2 3 4 5 6 7]


In [73]:
# insert into a rank 2 array
x = np.array([[1, 2, 3], [7, 8, 9]])
print(x)

# insert row
x = np.insert(x, 1, [4, 5, 6], axis=0)
print('\n', x)

# insert column
x = np.insert(x, 1, 5, axis=1)
print('\n', x)

[[1 2 3]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 5 2 3]
 [4 5 5 6]
 [7 5 8 9]]


In [76]:
# stacking arrays on top of each other or side by side. the shape must match.
x = np.array([1, 2])
print(x)

y = np.array([[3, 4], [5, 6]])
print('\n', y)

x1 = np.vstack((x, y))
print('\n', x1)

y1 = np.hstack((y, x.reshape(2, 1)))
print('\n', y1)

[1 2]

 [[3 4]
 [5 6]]

 [[1 2]
 [3 4]
 [5 6]]

 [[3 4 1]
 [5 6 2]]


### Slicing

In [77]:
x = np.arange(1, 21).reshape((4, 5))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [81]:
# slicing: first (start) index is included, second (end) index is excluded
# part 1 below is the indices to grab from rows, part 2 is the indices to grab from columns
y = x[1:4, 2:5]
print(y)

y = x[1:, 2:]
print('\n', y)

y = x[1:3, 3:5]
print('\n', y)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]

 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]

 [[ 9 10]
 [14 15]]


In [84]:
# grab a column
y = x[:, 2]
print(y)

# make it a column, not a row
y = x[:, 2:3] # this slicing method
print('\n', y)

[ 3  8 13 18]

 [[ 3]
 [ 8]
 [13]
 [18]]


In [85]:
# slicing creates a VIEW of the original array. changing elements in y would also change x.
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [86]:
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [88]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [89]:
# NOTICE, x has also changed
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [95]:
# to create a copy, use the np.copy function
x = np.arange(0, 20).reshape((4, 5))
print(x)

z = np.copy(x[1:, 2:])
print('\n', z)

z[2, 2] = 555
print('\n', z)

# NOTICE, x has NOT changed
print('\n', x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [98]:
x = np.arange(0, 20).reshape((4, 5))
print(x)

indices = np.array([1, 3])
print('\n', indices)

# get the second and fourth rows (indexes 1 and 3 for rows)
y = x[indices, :]
print('\n', y)

# get the second and fourth columns
z = x[:, indices]
print('\n', z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

 [1 3]

 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [100]:
print(np.diag(x))
print(np.diag(x, k=1)) # get elements 1 element directly above the diag
print(np.diag(x, k=-1)) # get elements 1 element directly below the diag


[ 0  6 12 18]
[ 1  7 13 19]
[ 5 11 17]


In [101]:
# get unique values
x = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
print(np.unique(x))

[1 2 3 5 8]


### Boolean indexing, set operations and sorting

In [102]:
x = np.arange(25).reshape((5, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [108]:
# use boolean expression to grab elements
print(x[x > 10])
print(x[x <= 7])
print(x[(x > 10) & (x < 17)])

# set those indices to a value
x[(x > 10) & (x < 17)] = -1
print('\n', x)

[17 18 19 20 21 22 23 24]
[ 0  1  2  3  4  5  6  7 -1 -1 -1 -1 -1 -1]
[]

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [113]:
# intersection, difference, union
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.setdiff1d(y, x))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[6 7 8]
[1 2 3 4 5 6 7 8]


#### Sorting

In [118]:
# sorting
x = np.random.randint(1, 11, size=(10,))
print(x)

# sort as function; sorts the array out of place, not changing the original array
print('\n')
print(np.sort(x))
print(x)

# sort as method; sorts the original array in place, changing it
print('\n')
x.sort()
print(x)

[9 8 3 6 6 2 8 8 8 6]


[2 3 6 6 6 8 8 8 8 9]
[9 8 3 6 6 2 8 8 8 6]


[2 3 6 6 6 8 8 8 8 9]


In [120]:
x = np.random.randint(1, 11, size=(5, 5))
print(x)

# sort by row
print(np.sort(x, axis=0))

# sort by column
print(np.sort(x, axis=1))

[[ 8  3  7  2 10]
 [ 6  7  8  1  8]
 [ 1  9  6  6  5]
 [ 2  3  3  5  6]
 [ 6 10  5  6  5]]
[[ 1  3  3  1  5]
 [ 2  3  5  2  5]
 [ 6  7  6  5  6]
 [ 6  9  7  6  8]
 [ 8 10  8  6 10]]
[[ 2  3  7  8 10]
 [ 1  6  7  8  8]
 [ 1  5  6  6  9]
 [ 2  3  3  5  6]
 [ 5  5  6  6 10]]


### Arithmetic operations and broadcasting

In [123]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

# add
print(x + y)
print(np.add(x, y)) # function approach usually has options we can tweak

# subtract
print(x - y)
print(np.subtract(x, y))

# multiply
print(y * x)
print(np.multiply(x, y))

# divide
print(x / y)
print(np.divide(x, y))

# in order to do this, numpy sometimes uses broadcasting: how numpy handles element-wise operations with arrays
# of different shapes. these arrays must be of the same shape, or broadcastable.

[ 6  8 10 12]
[ 6  8 10 12]
[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 0.2         0.33333333  0.42857143  0.5       ]


In [126]:
# element-wise arithmetic on rank 2 arrays
x = np.array([1, 2, 3, 4]).reshape((2, 2))
y = np.array([5, 6, 7, 8]).reshape((2, 2))

print(x)
print(y)
print(x + y)
print(np.add(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [127]:
# other mathematical functions
print(np.sqrt(x))
print(np.exp(x))
print(np.power(x, 2))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]
[[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]]
[[ 1  4]
 [ 9 16]]


In [134]:
print(x)
print('average of all: ', x.mean())
print('average of columns: ', x.mean(axis=0))
print('average of rows: ', x.mean(axis=1))
print('standard deviation: ', x.std())
print('median: ', np.median(x))
print('min: ', x.max())
print('max: ', x.min())

[[1 2]
 [3 4]]
average of all:  2.5
average of columns:  [ 2.  3.]
average of rows:  [ 1.5  3.5]
standard deviation:  1.11803398875
median:  2.5
min:  4
max:  1


In [135]:
# broadcasting "3" to each element, allowing us to add 3 to each in one line of code
print(x + 3)

[[4 5]
 [6 7]]


In [138]:
# print min of each column
# multi-dimensional
x = np.array([3, 2, 7, 9, 6, 8, 1, 4, 5]).reshape((3, 3))
print(x)

# print min of each col
x.min(axis=0)

[[3 2 7]
 [9 6 8]
 [1 4 5]]


array([1, 2, 5])