In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.random.randn(3,3)
print(a)
b = np.random.randn(3,1)
print(b)
c=a*b
print(c)

[[-2.33431235  0.67456686 -0.39053825]
 [-1.62434099  0.09185568 -0.1863716 ]
 [-1.67793332 -0.44606199  0.86886982]]
[[-0.7812266 ]
 [ 0.40829849]
 [-0.33185526]]
[[ 1.82362691 -0.52698958  0.30509887]
 [-0.66321597  0.03750453 -0.07609524]
 [ 0.55683099  0.14802802 -0.28833902]]
